TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_BOARD_PLATFORM := msm7x27a
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a5
TARGET_SPECIFIC_HEADER_PATH := device/samsung/kyleopen/include
TARGET_BOOTLOADER_BOARD_NAME := kyleopen
TARGET_PREBUILT_KERNEL := device/samsung/kernel.s7562
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_KERNEL_SOURCE := kernel/samsung/kyleopen
TARGET_KERNEL_CONFIG := cyanogenmod/kyle02_defconfig

BOARD_KERNEL_CMDLINE := console=ttyHSL0,115200,n8 andriodboot.hardware=qcom
BOARD_KERNEL_BASE := 0x00200000
BOARD_KERNEL_PAGESIZE := 4096

TARGET_GLOBAL_CFLAGS += -mtune=cortex-a5 -mfpu=neon -mfloat-abi=softfp
TARGET_GLOBAL_CPPFLAGS += -mtune=cortex-a5 -mfpu=neon -mfloat-abi=softfp

## Logging
#TARGET_GLOBAL_CFLAGS += -DLOG_NDEBUG=0
#TARGET_GLOBAL_CPPFLAGS += -DLOG_NDEBUG=0

## Bionic
TARGET_CORTEX_CACHE_LINE_32 := true
ARCH_ARM_HAVE_32_BYTE_CACHE_LINES := true
ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_USE_SPARROW_BIONIC_OPTIMIZATION := true

## OTA assert
TARGET_OTA_ASSERT_DEVICE := kyleopen,GT-S7562,S7562

## Recovery
TARGET_RECOVERY_INITRC := device/samsung/kyleopen/recovery/init.rc
TARGET_RECOVERY_FSTAB := device/samsung/kyleopen/recovery/recovery.fstab
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_CUSTOM_RECOVERY_KEYMAPPING := ../../device/samsung/kyleopen/recovery/recovery_keys.c
BOARD_CUSTOM_GRAPHICS := ../../../device/samsung/kyleopen/recovery/graphics.c
BOARD_HAS_SDCARD_INTERNAL := false
BOARD_HAS_DOWNLOAD_MODE := true
BOARD_USES_MMCUTILS := true
BOARD_HAS_NO_MISC_PARTITION := true
BOARD_FLASH_BLOCK_SIZE := 131072
RECOVERY_CHARGE_ENABLE := true

## Filesystem
BOARD_DATA_DEVICE := /dev/block/mmcblk0p25
BOARD_DATA_FILESYSTEM := ext4
BOARD_DATA_FILESYSTEM_OPTIONS := rw
BOARD_SYSTEM_DEVICE := /dev/block/mmcblk0p16
BOARD_SYSTEM_FILESYSTEM := ext4
BOARD_SYSTEM_FILESYSTEM_OPTIONS := rw
BOARD_CACHE_DEVICE := /dev/block/mmcblk0p17
BOARD_CACHE_FILESYSTEM := ext4
BOARD_CACHE_FILESYSTEM_OPTIONS := rw

## Partition sizes
BOARD_BOOTIMAGE_PARTITION_SIZE := 12582912
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 12582912
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1258291200
BOARD_USERDATAIMAGE_PARTITION_SIZE := 1946804224

## Boot
BOARD_WANTS_EMMC_BOOT := true
TARGET_NO_INITLOGO := true
TARGET_BOOTANIMATION_USE_RGB565 := true

## Graphics, media
#USE_OPENGL_RENDERER := true
#BOARD_USES_QCOM_HARDWARE := true
#TARGET_USES_OVERLAY := false
#TARGET_HAVE_BYPASS  := false
#TARGET_USES_GENLOCK := true
#TARGET_QCOM_HDMI_OUT := false
#TARGET_USES_ION := false
#BOARD_USES_QCOM_LIBS := true
#BOARD_EGL_CFG := device/samsung/kyleopen/prebuilts/egl.cfg
#COMMON_GLOBAL_CFLAGS += -DQCOM_HARDWARE

## Graphics, media
USE_OPENGL_RENDERER := true
TARGET_QCOM_DISPLAY_VARIANT := legacy
TARGET_NO_HW_VSYNC := true
BOARD_USES_QCOM_HARDWARE := true
BOARD_ADRENO_DECIDE_TEXTURE_TARGET := true
BOARD_USE_LEGACY_TOUCHSCREEN := false
BOARD_EGL_CFG := device/samsung/kyleopen/prebuilts/egl.cfg
COMMON_GLOBAL_CFLAGS += -DQCOM_LEGACY_OMX
COMMON_GLOBAL_CFLAGS += -DQCOM_HARDWARE -DANCIENT_GL

## Bluetooth
BOARD_HAVE_BLUETOOTH := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/samsung/kyleopen/bluetooth

## Webkit
ENABLE_WEBGL := true
TARGET_FORCE_CPU_UPLOAD := true

## Use device specific modules
TARGET_PROVIDES_LIBLIGHTS := true

